services:
  spring-boot-app:
    build:
      context: ./services  # Use the services directory as build context
      dockerfile: Dockerfile  # Use the Dockerfile in the services directory
    container_name: spring-boot-app
    environment:
      NEO4J_URI: "${NEO4J_URI}"
      NEO4J_USERNAME: "${NEO4J_USERNAME}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
    ports:
      - "8080:8080"  # Map application port to host

  vite-app:
    build:
      context: ./web  # Use the web directory as build context
      dockerfile: Dockerfile  # Specify the Dockerfile for Vite.js
      args:
        MODE: development  # Use development mode
    container_name: vite-app
    ports:
      - "3000:80"  # Map Vite app port to host
    depends_on:
      - spring-boot-app  # Ensure Spring Boot app starts before Vite app