services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/your_secure_password
    volumes:
      - neo4j-data:/data  # Persist data between restarts

  spring-boot-app:
    build:
      context: ./services  # Use the services directory as build context
      dockerfile: Dockerfile  # Use the Dockerfile in the services directory
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # Map application port to host
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=your_secure_password
    depends_on:
      - neo4j  # Ensure Neo4j starts before the Spring Boot app

  vite-app:
    build:
      context: ./web  # Use the web directory as build context
      dockerfile: Dockerfile  # Specify the Dockerfile for Vite.js
    container_name: vite-app
    ports:
      - "3000:80"  # Map Vite app port to host
    depends_on:
      - spring-boot-app  # Ensure Spring Boot app starts before Vite app

volumes:
  neo4j-data:  # Named volume for persisting Neo4j data